auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: lirenlong.github.io
url: http://lirenlong.github.io
feed: /atom.xml
author_info: <a href="http://lirenlong.github.io/">RogerAce</a>
