auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: rogerace.github.com
url: http://rogerace.github.com
feed: /atom.xml
author_info: <a href="http://rogerace.github.com/">RogerAce</a>
